### ISSUE TITLE
Release Kuirl 2019-08

### ISSUE THREAD

**Issue by subotic** [dasch-swiss/dsp-meta#16]
Please add the versions of all apps that need to be re-deployed.

**Comment by kilchenmann** [comment]
It's [version 1.4.0 of Kuirl](https://github.com/dhlab-basel/Kuirl/releases/tag/v1.4.0) only

**Comment by subotic** [comment]
What about BEOL. Nothing to do there? Who is actually responsible for BEOL?

**Comment by flavens** [comment]
Tobias is for now responsible for BEOL. No idea if there is something to do for this release..

**Comment by kilchenmann** [comment]
For the Knora Web App we have to use version 1.5.0 together with Knora v9.0.0
Docker is building the new package at the moment.

For Beol I try to update today and on the weekend. This will be version 1.5.0 as well. This can be reviewed on Monday and builded then as well.
